### ISSUE TITLE
Support for message formats other than ICU

### ISSUE THREAD

**Issue by ilanbm** [amannn/next-intl#10]
looking for libraries to use for i18n I was surprised to see how many echo systems there are for the locale messages themselves. 
It seemed like they live in different worlds since all libraries don't even address supporting the formats, so the market is very fragmented and not efficient.

So I think it would be smart to support other formats, a low-hanging fruit to achieve more users/dev.

For example, the i18next default format is different than the 'ICU' standard used here in next-intl. 
I don't know how really different it is (I'm not using all features, like plural and date formating etc...), but I think that the diff is easy to work with.

In my case trying next-intl on locales from an i18next project, I had to do just two things:
1. variables: replace in locale files all `{{ name }}` with ICU's `{name}`  (one `{` instead of two)
I wrote this regex for it: `.replace(/\{\{ *(\w+) *\}\}/g, '{$1}')`
2. name space delimiter: replace all keys used in code from `NAMESPACE: etc..` with `NAMESPACE. etc`  (`.` instead of `:`)

So actually supporting i18next default format seems to be very easy.
(and my motivation to not use i18next on a nextjs project was a heavy performance hit on client side, including having all languages locales sent to browser)
- I guess I'm not alone in that, there should be a simple way to be versatile with the formats

**Comment by amannn** [comment]
Thanks for opening this!

I have a bit of experience with i18next but from what I saw so far it is similar in things like interpolation, but differs quite a bit with more sophisticated features. E.g. for plurals and select you have to use different messages that are then embedded within the original message. With ICU there's just one message, which is a large factor why I prefer that syntax.

I'm not sure if there's support for `selectordinal` in `i18next` and rich text would require a different API at the call site (array instead of object, or alternatively indices as keys).

This library is quite integrated with the ICU functionalities at this point. To support a different syntax, forking the library might be the easier choice.

However what I think could be interesting is a migration guide from i18next to ICU / this lib, possibly with automated tools helping in the process.

I don't have any plans yet to support other localisation syntax, but I'll leave this open to see if there's more interest.

> (and my motivation to not use i18next on a nextjs project was a heavy performance hit on client side, including having all languages locales sent to browser)

Glad to hear if this lib helps with this!

**Comment by ilanbm** [comment]
It makes sense I guessed there is more to it in the plurals area, I've never used it... 
For my usage the transformation was quick and simple.

I wonder if there are already migration scripts between them and other formats.

Thanks for the response, I'll keep an eye here also

**Comment by amannn** [comment]
There's `Intl.MessageFormat` on the horizon which uses the Message Format 2 syntax. It's still under heavy development, but if this makes it into the browsers that should probably be a format we should support since it will decrease the library size significantly if we don't have to bundle a parser.

**Comment by jamuhl** [comment]
@ilanbm and others stumbling onto this. i18next is built to only load what is needed (separation of languages, namespaces) -  running into performance issues where the clientside loads all languages and namespaces is basically a result of not using it right -> using next-i18next (or at least following how to do it right) will help: https://github.com/i18next/next-i18next

**Comment by amannn** [comment]
@jamuhl I'm sorry, I can't follow how that is related to this issue? Also please note that `next-intl` is not affiliated with i18next.

**Comment by jamuhl** [comment]
it's related to

> (and my motivation to not use i18next on a nextjs project was a heavy performance hit on client side, including having all languages locales sent to browser)

just wanted to make clear that i18next does not have that problems mentioned (for others coming here)

**Comment by amannn** [comment]
Ah ok, I see! Good to hear! 🙌

**Comment by amannn** [comment]
I'll close this issue, since other message formats are currently not planned.
