### ISSUE TITLE
[TypeScript] TimeZone type

### ISSUE THREAD

**Issue by adammehdaoui** [amannn/next-intl#1003]
### Is your feature request related to a problem? Please describe.

Hey, I'm having trouble accessing the TimeZone type from the lib.
I need it to pass the useTimeZone() return variable as prop to a provider component.

### Describe the solution you'd like

Accessing TimeZone type from the lib (example: import type {TimeZone} from "next-intl")

### Describe alternatives you've considered

Copy-paste all the TimeZone type locally.

**Comment by amannn** [comment]
`next-intl` only provides auto-complete for the `timeZone` prop in `i18n.ts` and `NextIntlProvider`, but ultimately any string is accepted:

https://github.com/amannn/next-intl/blob/9c54d623ed39d251c59a0cde58a17452524ff96b/packages/use-intl/src/core/TimeZone.tsx#L424

This is because there might be time zones that are not present in the list. We do try to make it easy to pick a correct one with the auto-complete TypeScript hack.

Therefore to pass the time zone to another component or function, you should be able to type it just as `string`. Does that work for you?

**Comment by adammehdaoui** [comment]
Hey, your solution works fine for me. I just thought the fact I was unable to access TimeZone type was something I could fix by accessing another package

I finally used the useTimeZone hook returned value like this to handle the possibility of undefined :

`const timeZone = useTimeZone()`
`const timeZoneCode = timeZone ? timeZone.toString() : "UTC"`

Thanks for your response. Have a good week-end!
