### ISSUE TITLE
Support Intl.RelativeTimeFormat for `relativeTime` formatting

### ISSUE THREAD

**Issue by kvnxiao** [amannn/next-intl#1056]
### Is your feature request related to a problem? Please describe.

Currently, the formatter for [`Formatting date and time ranges`](https://next-intl-docs.vercel.app/docs/usage/dates-times#date-time-ranges) does not support additional configuration other than specifying the exact unit to display the output in.

The relative time formatting should support all the options from [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) and not just `RelativeTimeFormatUnit`

### Describe the solution you'd like

Instead of:

```typescript
type RelativeTimeFormatOptions = {
    now?: number | Date;
    unit?: Intl.RelativeTimeFormatUnit;
};
export default RelativeTimeFormatOptions;
```

The `RelativeTimeFormatOptions` type should also accept the options from the [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat#options) constructor:
* numberingSystem
* style
* numeric

### Describe alternatives you've considered

The only alternative would be to use the native `Intl` API directly, but this should be integrated into the formatter in `next-intl` IMO

**Comment by amannn** [comment]
Hey, thanks for the report! I agree, we could definitely support `numberingSystem` and `style`. As for `numeric` I'm a bit hesitant though, as it can lead to issues when values are rounded: https://github.com/amannn/next-intl/pull/765.

Do you need `numeric` for your use case? If so, can you include further details?

I've added #1057 to look into this.

**Comment by kvnxiao** [comment]
At the moment, I only have a need for the `style` to specify `long`, `short`, or `narrow`.

I think numberingSystem and style is sufficient for now!

**Comment by amannn** [comment]
Sounds good, thanks for the feedback!

**Comment by amannn** [comment]
Interesting. Can you share what your exact use case is?

From my personal observation, "yesterday" is a nice thing to read, but it's easy to run into a wrong output due to rounding (see https://github.com/amannn/next-intl/issues/1056#issuecomment-2097876494). "Yesterday" might not actually be the day before today, but could be the day before yesterday.

**Comment by kvnxiao** [comment]
The use case is exactly as described, requiring the use of localizations for "yesterday" and "today". I don't think we should be too worried about the rounding because IMO the idea is that doing the correct math beforehand is a prerequisite that's on the onus of the developer (otherwise it wouldn't make much sense for the official `Intl.RelativeTimeFormat` to also exist).

For what it's worth, what I'm currently doing is I'm using Luxon to do proper date-time calculations of the math in "days" (with the local machine timezones set) via `dateTime.startOf('day')`, before converting it back into a JS `Date` and passing it into the `Intl.RelativeTimeFormat` with `numeric: auto`.

**Comment by kvnxiao** [comment]
Let me know if you would like me to open a new issue to track this discussion!

**Comment by amannn** [comment]
> The use case is exactly as described, requiring the use of localizations for "yesterday" and "today"

The current output would be "1 day ago" instead of "yesterday". I'd say that "yesterday" reads a bit nicer, but the rounding problem make this a bit error prone. Is there a particular issue with using "1 day ago" in your app?

> otherwise it wouldn't make much sense for the official `Intl.RelativeTimeFormat` to support `numeric: "auto"`



So with `auto`, you either get values like "yesterday" (for integers) or "1.1 days ago" (for floating point numbers). That's when you're using `Intl.RelativeTimeFormat` yourself—without `next-intl`.

However, `next-intl` does rounding internally in order to render more readable values like "1 day ago"—an approximation.

https://github.com/amannn/next-intl/blob/9a70cef9f7d36cde5e8a69fd380f0747a050be56/packages/use-intl/src/core/createFormatter.tsx#L69-L71

The [docs](https://next-intl.dev/docs/usage/dates-times#relative-times) mention this capability:

> Note that values are rounded, so e.g. if 126 minutes have passed, “2 hours ago” will be returned.

So if `next-intl` would allow to pass `numeric: 'auto'` we'd have the user run into problematic scenarios due to rounding. If you're using `Intl.RelativeTimeFormat` directly, the rounding is on you. It seems to me like that puts you in a better position than if `next-intl` would support this.

That's at least my current understanding. I might have to give this more thought, but it seems like a potentially problematic feature to support.

What do you think?

**Comment by kvnxiao** [comment]
> Is there a particular issue with using "1 day ago" in your app

Yes, the designers specifically want more friendly localized dates for "today" and "yesterday", instead of "1 day ago".

Currently I'm fetching the locale via next-intl's `useLocale` and passing it into `Intl.RelativeTimeFormat` directly. May I ask, what's wrong with trying to support the same feature set as `Intl.RelativeTimeFormat` directly? The onus is already on the developer to make sure they're doing the rounding properly when using `Intl.RelativeTimeFormat` and `numeric: auto`, so can we not just document that as a caveat and mirror it's behaviour in `next-intl` directly?

**Comment by kvnxiao** [comment]
Also as a side note, in other languages, the equivalent localizations of "yesterday" as opposed to "1 day ago" and "today" instead of "in 0 days" sounds much less awkward.

In Chinese for example, "1 day ago" is "1天前", but this is not a phrase that anyone would ever use colloquially, the better way would be "昨天" which transliterates to "yesterday". And for "in 0 days", the phrase "0天后" wouldn't even make sense to use anywhere and would actually seem like an error whereas "今天" is the correct translation for "today".

The point of this add-on comment here is to express why `numeric: auto` in `Intl.RelativeTimeFormat` has value existing, and my hope here is for `next-intl` to support the same options directly within the library so that I can achieve the same thing via `useFormatter` without having to manually pass around a locale string + constructing a new `Intl.RelativeTimeFormat`er for the sole purpose of using  `numeric: auto` on rare occasions.

**Comment by amannn** [comment]
Hmm, I have another idea here.

What if `next-intl` would detect if rounding is necessary, and if not, we could switch to `numeric: 'auto'`. That would avoid the footgun of using `numeric: 'auto'` with rounded values and I think would also cover your case.

Here's a PR with a proposal: https://github.com/amannn/next-intl/pull/1872.

What do you think? I might have to give it another thought and see if this feels right when writing docs, but it could be an option.

**Comment by amannn** [comment]
@kvnxiao Do you by chance have an idea if this code snippet could be simplified? 

https://github.com/amannn/next-intl/pull/1872/files#r2071663776

**Comment by kvnxiao** [comment]
I like the idea so far, took a look over the PR itself and had left a comment: https://github.com/amannn/next-intl/pull/1872/files#r2072115257
