### ISSUE TITLE
Error in 13.14.0: Expected a suspended thenable

### ISSUE THREAD

**Issue by jonathanwilke** [amannn/next-intl#1072]
### Description

Hey,

when I upgrade next-intl to 13.14 in my Next app, I can't start my app anymore and it gives me the following error:

<img width="1452" alt="Bildschirmfoto 2024-05-17 um 16 22 51" src="https://github.com/amannn/next-intl/assets/1453455/b7c832a5-0b40-4969-b9fe-bf0cd816fa40">

Any idea what's wrong here? Is it a bug in the lib or is there a misconfiguration on my side?

### Verifications

- [X] I've verified that the problem I'm experiencing isn't covered in [the docs](https://next-intl-docs.vercel.app/).
- [X] I've searched for similar, existing issues on GitHub and [Stack Overflow](https://stackoverflow.com/search?q=next-intl).
- [X] I've compared my app to [a working example](https://next-intl-docs.vercel.app/examples) to look for differences.

### Mandatory reproduction URL

#

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

No error

**Comment by amannn** [comment]
Hey, is this from supastarter? Can you share a branch or PR with me where I can take a look?

**Comment by jonathanwilke** [comment]
Yes it is. You can simply checkout main and install next-intl 13.14.0 and the error will occur on `pnpm dev`.

**Comment by amannn** [comment]
I've added a PR with a fix!

For others who come across this: The problem was that the root layout was `async`, but `useLocale` was called there. Apparently this has worked previously, but hooks should generally not be called in `async` components. React doesn't support this and as far as I know will also show an ESLint warning for this case in the future.

The fix was to use `const locale = await getLocale()` instead.
