### ISSUE TITLE
Lazy-load intl-messageformat

### ISSUE THREAD

**Issue by EliasVal** [amannn/next-intl#1083]
### Is your feature request related to a problem? Please describe.

While building my Next.js app, I noticed that `intl-messageformat` is taking up quite a bit of space. 

`page.tsx` with `useTranslations`:
![image](https://github.com/amannn/next-intl/assets/46247153/a0009bd7-81de-4650-bebc-e96a9332b823)

`page.tsx` without `useTranslations`:
![image](https://github.com/amannn/next-intl/assets/46247153/2b0f4efd-9ebd-40d8-af89-b8c1e6b6c4df)

Bundle analyzer result with `useTranslaions`:
![image](https://github.com/amannn/next-intl/assets/46247153/d8e0a58a-9c56-45d4-a86a-55fbb72697ec)

### Describe the solution you'd like

Either have the option to somehow opt-out of formatting, or lazy-load it on the client.

### Describe alternatives you've considered

Haven't looked into any other solutions.

**Comment by amannn** [comment]
Thanks you for the question! It's indeed planned to get rid of `intl-messageformat` on the client side, please see https://github.com/amannn/next-intl/issues/962.

For the time being, staying with [translations within Server Components](https://next-intl-docs.vercel.app/docs/environments/server-client-components#using-internationalization-in-client-components) can be an alternative to avoid loading `int-messageformat` on the client side.

Hope this helps!

**Comment by EliasVal** [comment]
@amannn Thanks for the quick reply and the amazing work on the package! What's the progress on #705 ? (And as for your comment on an issue I posted a while back, the new option to opt out of the i18n routing works flawlessly!)

**Comment by amannn** [comment]
You can follow https://github.com/amannn/next-intl/pull/705 for the latest progress, but it's still a bit early. There are currently a few other priorities, but I'd like to get back to that PR as soon as I find the time. I can't really give an estimate currently, but the feature is rather months away I guess.

Since it's quite a change, there might be an opt-in experimental flag in the future to get feedback from early adopters. Might take a bit for the feature to stabilize, also `icu-to-json` that's mentioned in the PR is experimental at this point.

If you subscribe to the PR or the issue, I can keep you in the loop!

> And as for your comment on an issue I posted a while back, the new option to opt out of the i18n routing works flawlessly!

Cool, that's nice to hear! 🙌
