### ISSUE TITLE
Allow usage of markup in addition to rich values in defaultTranslationValues

### ISSUE THREAD

**Issue by neverether** [amannn/next-intl#1181]
### Is your feature request related to a problem? Please describe.

In my app I'm using both `t.rich` and `t.markup` relatively often, and the majority of the tags in use are common ones like: `strong`, `br`, `i`, etc. For `rich` translations, I'm utilizing `defaultTranslationValues` in my provider but I'd also like to specify the appropriate strings for the same tags except for `markup` support. 

### Describe the solution you'd like

Potentially extending the config of `defaultTranslationValues`?

### Describe alternatives you've considered

Haven't come up with an idea yet.

**Comment by amannn** [comment]
Hmm, I see. Therefore the default values you provide for `t.rich` can't be used for `t.markup` since in one case they should return React elements and in the other plain strings, right?

There's currently a discussion around whether `defaultTranslationValues` should be deprecated in https://github.com/amannn/next-intl/issues/611, as it has a few issues:
1. We can't add strict TypeScript validation for args passed to `t` if there are potential global values.
2. The default values can't be serialized across the Server Components boundary to be made automatically available in Client Components.
3. Your issue described here (new)

There hasn't been a decision around this yet, but your issue seems to add one more bullet to this list. For the time being, I'd suggest looking into the alternatives mentioned in #611 and use one of those patterns.

Hope this helps!

**Comment by neverether** [comment]
> Hmm, I see. Therefore the default values you provide for t.rich can't be used for t.markup since in one case they should return React elements and in the other plain strings, right?

That's exactly right.

Apologies, I didn't find that topic when searching earlier. For what it's worth, when going through the documentation for the first time (I just migrated my entire app from `next-i18next`), I thought the global `defaultTranslationValues` was potentially a double-edge sword as it also potentially obfuscates the full set of values to a newly onboarded team member for instance. 

I personally wouldn't mind doing something like: `{t.rich("foo."), { ...defaultRichValues, foo: (...)})` in any case. It's a little verbose but more very explicit.
