### ISSUE TITLE
router issue when switching locale: path.startsWith is not a function

### ISSUE THREAD

**Issue by chaotic-justice** [amannn/next-intl#1240]
### Description

![image](https://github.com/user-attachments/assets/53f786e3-e504-4456-a0ba-34755c2b2020)

![image](https://github.com/user-attachments/assets/c05cccad-bc7c-49a2-a1db-82f8b6708c30)

TypeError: path.startsWith is not a function
encountered when switching locale

### Verifications

- [X] I've verified that the problem I'm experiencing isn't covered in [the docs](https://next-intl-docs.vercel.app/).
- [X] I've searched for similar, existing issues on GitHub and [Stack Overflow](https://stackoverflow.com/search?q=next-intl).
- [X] I've compared my app to [a working example](https://next-intl-docs.vercel.app/examples) to look for differences.

### Mandatory reproduction URL

https://github.com/chaotic-justice/summer-bee

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on `git clone`
3. run `yarn && yarn dev`
4. See error: … 

### Expected behaviour

switching to a diff locale will trigger the routing error

**Comment by r0skar** [comment]
I am seeing the same issue.

```bash
"next": "14.2.5",
"next-intl": "3.17.2",
```

**Comment by meabed** [comment]
I have the same issue

**Comment by tgdn** [comment]
Same issue

**Comment by nahsooyeon** [comment]
```tsx
import { useParams} from "next/navigation";
import { usePathname, useRouter } from "@/i18n";
....

  const router = useRouter();
  const pathname = usePathname();
  const params = useParams();
  const [isPending, startTransition] = useTransition();


  const changeLanguage = (newLocale: string) => {
    const nextLocale = newLocale;
    startTransition(() => {
      router.replace(pathname, {
        // @ts-expect-error -- TypeScript will validate that only known `params`
           locale: nextLocale
         })
    })
  };
  ```

I solved the issue on this way.

**Comment by NaderTate** [comment]
I do that as a workaround:
`<button
                    onClick={() => {
                      startTransition(() => {
                        const newPath = pathname.replace(
                          lang,
                          lang === "en" ? "ar" : "en"
                        );
                        push(newPath, { scroll: false });
                      });
                    }}
                  >
                    {lang === "en" ? "AR" : "EN"}
                   
                  </button>`

**Comment by tgdn** [comment]
Same issue

**Comment by tgdn** [comment]
You can simply call `router.replace` with the same pathname and the updated locale as follows to update the locale: 

```
startTransition(() => {
  router.replace(pathname, { locale: nextLocale });
});
```

**Comment by tgdn** [comment]
@danielkoller I'm unsure, I tried and it worked.

**Comment by amannn** [comment]
I've just checked the reproduction from @chaotic-justice and saw that [the call to `router.push` is invalid](https://github.com/chaotic-justice/summer-bee/blob/b3ecfddf34faeb3dbaa29235db37e762178d17b0/components/header/LocaleSwitcherSelect.tsx#L27-L33).

There seems to be a confusion between `createSharedPathnamesNavigation` and `createLocalizedPathnamesNavigation`. 

In case of localized pathnames, you can call `router.push` with an object like `{pathname: '/user/[userId], params: {userId: 2}}` which allows to resolve a localized template. With shared pathnames however, pathnames are the same for each locale, therefore there's no need to resolve a localized template. Due to this, `router.push` only accepts a string argument.

```tsx
const router = useRouter();
const pathname = usePathname();

// ❌ Doesn't work
router.push({pathname}, {locale: 'de'});

// ✅ Works
router.push(pathname, {locale: 'de'});
```

This matches what @tgdn [mentioned above](https://github.com/amannn/next-intl/issues/1240#issuecomment-2288033394).

See also [How can I change the locale for the current page?](https://next-intl-docs.vercel.app/docs/routing/navigation#userouter-change-locale) in the docs (make sure you have "Shared pathnames" selected in the tabs above).

After this fix, the call in the reproduction from @chaotic-justice works for me.

Note however that there are other bugs in the reproduction that need to be resolved for the app to work for me:
1. The `[lang]` segment needs to be renamed to `[locale]` (make sure to adjust the received props in pages and layouts)
2. The layout needs to be moved to the `[locale]` folder.

You might want to review the getting started docs.

Hope this helps others who ran into this issue!

**Comment by giuppidev** [comment]
> I've just checked the reproduction from @chaotic-justice and saw that [the call to `router.push` is invalid](https://github.com/chaotic-justice/summer-bee/blob/b3ecfddf34faeb3dbaa29235db37e762178d17b0/components/header/LocaleSwitcherSelect.tsx#L27-L33).
> 
> There seems to be a confusion between `createSharedPathnamesNavigation` and `createLocalizedPathnamesNavigation`.
> 
> In case of localized pathnames, you can call `router.push` with an object like `{pathname: '/user/[userId], params: {userId: 2}}` which allows to resolve a localized template. With shared pathnames however, pathnames are the same for each locale, therefore there's no need to resolve a localized template. Due to this, `router.push` only accepts a string argument.
> 
> ```tsx
> const router = useRouter();
> const pathname = usePathname();
> 
> // ❌ Doesn't work
> router.push({pathname}, {locale: 'de'});
> 
> // ✅ Works
> router.push(pathname, {locale: 'de'});
> ```
> 
> This matches what @tgdn [mentioned above](https://github.com/amannn/next-intl/issues/1240#issuecomment-2288033394).
> 
> See also [How can I change the locale for the current page?](https://next-intl-docs.vercel.app/docs/routing/navigation#userouter-change-locale) in the docs (make sure you have "Shared pathnames" selected in the tabs above).
> 
> After this fix, the call in the reproduction from @chaotic-justice works for me.
> 
> Note however that there are other bugs in the reproduction that need to be resolved for the app to work for me:
> 
> 1. The `[lang]` segment needs to be renamed to `[locale]` (make sure to adjust the received props in pages and layouts)
> 2. The layout needs to be moved to the `[locale]` folder.
> 
> You might want to review the getting started docs.
> 
> Hope this helps others who ran into this issue!

Hi, how to push with shared pathnames passing a query param? Accepting only a string as you mention I cannot accomplish it. Thnaks

**Comment by amannn** [comment]
@giuppidev Same as with the regular Next.js [`redirect`](https://nextjs.org/docs/app/api-reference/functions/redirect):

```tsx
redirect('/users?page=2');
```

**Comment by giuppidev** [comment]
> @giuppidev Same as with the regular Next.js [`redirect`](https://nextjs.org/docs/app/api-reference/functions/redirect):
> 
> ```tsx
> redirect('/users?page=2');
> ```

I was using it, but got an error on email string (with the `+` special char). So in next I would pass an object to push instead of a string.

**Comment by amannn** [comment]
Oh sorry, you meant `useRouter().push`.

>  So in next I would pass an object to push instead of a string.

Next.js also only supports a string argument for `href` in push:

![Screenshot 2024-09-20 at 15 27 31](https://github.com/user-attachments/assets/a10d8e62-43a5-42de-8b9b-b824215d2105)

([source](https://nextjs.org/docs/app/api-reference/functions/use-router#userouter))

If you encounter an error, can you share a reproduction that works with Next.js but not with `next-intl`?
