### ISSUE TITLE
Middleware should gracefully handle unsupported but valid locale identifiers

### ISSUE THREAD

**Issue by rossyman** [amannn/next-intl#1252]
### Is your feature request related to a problem? Please describe.

Given the default setup for a `next-intl` app router based project with i18n routing. When you navigate to an unsupported locale, but where the locale identifier in the URL is still valid, `next-intl` will continue to redirect the user to the default locale specified in the configuration, and then append the valid but unsupported locale to the new URL, rather than directly throwing a 404.

Example of rewrites for a scenario where I support English and German and have English set as the default language, and then try to navigate to the unsupported Japanese locale:

```
domain.com/ -> domain.com/en
domain.com/en -> No redirect
domain.com/de -> No redirect
domain.com/jp -> domain.com/en/jp (404)
```

You can see the above in action on the [app router demo](https://next-intl-example-app-router.vercel.app) (Add `/jp` to the end of this)

### Describe the solution you'd like

The desired behaviour would be that `next-intl` could gracefully handle the `domain.com/jp` scenario, and return a 404 directly from `domain.com/jp`, rather than redirecting to `domain.com/en/jp` and then returning a 404.

This could potentially be done through something similar to the following code snippet, where when determining whether to redirect or not before throwing a 404, we could pass in the first path segment in the URL for validation:

```ts
const isValidLocale = (localeSegment: string): boolean => {
  try {
    new Intl.Locale(localeSegment).maximize()
    return true
  } catch (e) {
    return false
  }
}
```

Calling `.maximize()` seems to be the only consistent way I've found that we can trigger an exception when passing in invalid locales to JS's Locale API.

### Describe alternatives you've considered

The only other alternatives I've considered are totally removing i18n routing from my next-intl project. However, that comes with it's own tradeoffs and I'd rather have a more holistic solution similar to what is outlined above. It's not really a dealbreaker for me, but would be nice to have this gracefully handled.

**Comment by amannn** [comment]
I certainly see your point, but I can see two issues with this:
1. **False positives**: E.g. `/it` could either mean Italian, or information technology. I don't think it's safe to assume that anything that looks like a locale must be a locale.
2. **Unstyled 404**: Responding with a 404 status code from a middleware simply returns the status code and doesn't allow sending a rendered 404 page.

Due to this, I'm afraid there's not really a good way for `next-intl` to support this.

You can however [compose the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) and add this handling on top if you like.

Hope this helps!
