### ISSUE TITLE
t is not a function

### ISSUE THREAD

**Issue by imbhargav5** [amannn/next-intl#1326]
### Description

I see `t is not a function` error when I try to use the Link component exported by `@/i18n/routing`. My understanding is that the Link component is implemented independently in both server and client component environments and should work in both places. However, I am running into this issue in the server environment and the client environment works fine. 

![image](https://github.com/user-attachments/assets/92fca473-75e6-4461-9982-711ee79a00c2)

### Verifications

- [X] I've verified that the problem I'm experiencing isn't covered in [the docs](https://next-intl-docs.vercel.app/).
- [X] I've searched for similar, existing issues on GitHub and [Stack Overflow](https://stackoverflow.com/search?q=next-intl).
- [X] I've compared my app to [a working example](https://next-intl-docs.vercel.app/examples) to look for differences.

### Mandatory reproduction URL

https://github.com/imbhargav5/next-intl-bug-repro

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Start dev server on 3000
3.  Home page will error on the server

### Expected behaviour

There should be no `t is not a function` error in the server side and the Link function should use the current locale from cache and navigate correctly.

**Comment by amannn** [comment]
Your example is broken because you've specified [the wrong path in `next.config.mjs`](https://github.com/imbhargav5/next-intl-bug-repro/blob/177b25c340108ea9caa2e8a5ff9b979fd97a5e9d/next.config.mjs#L5). Please make sure to link to your _request_ configuration, not your _routing_ configuration. If you remove the override in the reproduction, then your `i18n/request.ts` file is picked up correctly.

I've added https://github.com/amannn/next-intl/pull/1327 to introduce error handling for this case, thanks for the report!

**Comment by imbhargav5** [comment]
Amazing. Your speed is next level. Thanks for this amazing project good sir!

**Comment by amannn** [comment]
Awesome, happy to help! 😊
