### ISSUE TITLE
Automatically build examples after installing dependencies in the repo

### ISSUE THREAD

**Issue by Kasea** [amannn/next-intl#141]
### Description

Cloned the repo and tried to run example locally, but i keep getting the below error.

```
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./src/pages/_app.tsx:1:0
Module not found: Can't resolve 'next-intl'
> 1 | import {NextIntlProvider} from 'next-intl';
  2 | import {AppProps} from 'next/app';
  3 | 
  4 | export default function App({Component, pageProps}: AppProps) {

https://nextjs.org/docs/messages/module-not-found
```

### Reproduction

Steps to reproduce:

1. git clone https://github.com/amannn/next-intl
2. cd next-intl
3. yarn install && yarn workspace example dev

NOTE: tried various methods of 3, but none seemed to have worked and yielded the same error

### Expected behaviour

Expect it to boot up and be accessible on localhost:3000

### Additional information

The root node_modules seems to be setup correctly, it symlinks the workspaces properly, but it seems like it doesn't resolve the parent's node_modules inside of the packages.

Node version: 16.10.0
Yarn version: 1.22.19

**Comment by amannn** [comment]
Hey and thanks for the report! The reason is likely that `use-intl` and `next-intl` need to be built first in the project. That's what I'm doing on CI:

https://github.com/amannn/next-intl/blob/6c26d0ae98f1c0ccd93ce55efe6ef5d26c07f994/.github/workflows/main.yml#L16-L17

Maybe we could include a postinstall step that does this. I'd be happy to review a PR if you'd like to contribute this change!

Otherwise the examples are also deployed on CodeSandboxe if you want to play around: https://next-intl-docs.vercel.app/examples/minimal

**Comment by Kasea** [comment]
Yeah that did it, I'll be adding the postinstall to my PR when I submit it. Although might still be confusing for people looking to contribute since the build will be required to be ran for every change, but I suppose that might be the norm for workspace projects, not sure as this is the first time I'm working with one.

**Comment by amannn** [comment]
Yep, that's my local workflow as well where I rebuild packages after changes when trying them out in examples. I see that it's a bit a hurdle, but I'm unfortunately not aware of a better solution. On CI the workflow is managed, so we can rely on up-to-date versions across the workspaces for the tests.

Thanks!

**Comment by amannn** [comment]
I've added a [contributors guide](https://github.com/amannn/next-intl/blob/main/CONTRIBUTORS.md) now that covers the getting started steps.
