### ISSUE TITLE
Type of TranslationValue for `t.rich` should include Element.JSX

### ISSUE THREAD

**Issue by votrungquan1999** [amannn/next-intl#1567]
## When using `t.rich` for rich text format, I see that I can use `JSX.Element` for the value, which displays correctly. However, the typescript gave me the error.

```
Type 'Element' is not assignable to type 'TranslationValue | ((chunks: ReactNode) => ReactNode)'
```

I think the library used under the hood also supports `JSX.Element` when formatting rich text. we could improve the typing here.

## Another issue is that in the server component that renders the formatted key, this error happens

```
[ Server ] Each child in a list should have a unique "key" prop.
```

### Verifications

- [X] I've verified that the problem I'm experiencing isn't covered in [the docs](https://next-intl-docs.vercel.app/).
- [X] I've searched for similar, existing issues on [GitHub](https://github.com/amannn/next-intl/issues) and [Stack Overflow](https://stackoverflow.com/search?q=next-intl).
- [X] I've compared my app to [a working example](https://next-intl-docs.vercel.app/examples) to look for differences.

### Mandatory reproduction URL

https://github.com/votrungquan1999/reproduce-next-intl-typing

### Reproduction description

1. Run npm run dev
2. see that the `Seconds` component is rendered by the `t.rich`
3. See the error report on the left side

https://github.com/user-attachments/assets/fe348f0e-a894-42d6-a08c-194f0769055b

### Expected behaviour

- Typescript should not throw an error when injecting JSX
- The children with no key error should not happen

**Comment by amannn** [comment]
There's a note on this in the docs: [How can I use “self-closing” tags without any chunks?](https://next-intl-docs.vercel.app/docs/usage/messages#rich-text-self-closing).

This currently has some benefits related to upcoming [type-safety of ICU args](https://x.com/jamannnnnn/status/1858906932448305404) in the upcoming `next-intl@4.0`. If we'd accept `ReactNode`, this would for example also allow `number`, therefore defeating [number formatting validation](https://x.com/jamannnnnn/status/1859143968904319352).

Due to this, I think it's not worth it changing this behavior for the time being.

**Comment by votrungquan1999** [comment]
Ok, I see. I also read the docs: [How can I use “self-closing” tags without any chunks?](https://next-intl-docs.vercel.app/docs/usage/messages#rich-text-self-closing) before posting this, but I think allowing ReactNode would make the message cleaner. 

Anyways, I see your point on the number format validation and really look forward to working with it

**Comment by amannn** [comment]
Sounds good, I'll close this for the time being then!
