### ISSUE TITLE
Error on production build with next@13.1.4

### ISSUE THREAD

**Issue by barbarah** [amannn/next-intl#172]
### Description

I am trying to get next-intl (beta) working on an app with next@13.1.4. Only with a production build, I'm getting the error:

"Error: Page changed from static to dynamic at runtime /en, see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error"

A development build (`next dev`) will work.

### Reproduction URL (CodeSandbox)

https://codesandbox.io/p/sandbox/next-intl-template-forked-27y3in

### Reproduction description

The easiest way to reproduce is by checking out the official example project https://github.com/amannn/next-intl-example-next-13

- Run a production build (`next build` then `next start`)
- This will work perfectly
- Then update next to 13.1.4
- Run a production build (`next build` then `next start`)
- The app will show an error

### Expected behaviour

A working app example app with the newest next version (now 13.1.4)

**Comment by barbarah** [comment]
Problem is fix by adding this to `/app/[locale]/layout.tsx`

```
export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'de'}];
}
```

**Comment by amannn** [comment]
Hi and thanks a lot for reporting this!

That's definitely a bug on the Next.js side, but luckily it's already fixed: https://github.com/vercel/next.js/issues/45134#issuecomment-1401196633. You might want to stay on v13.1.1 for now until 13.1.6 is released.

I tried out 13.1.6-canary.0 in the repo, that seems to work too. Interestingly all pages are generated as static with that release, I didn't think that was possible, since `next-intl` uses `headers()`—but somehow the page now qualifies for being static 🤷‍♂️.

I'll close this for the time being, as this should be fixed upstream—hope that's ok for you!

**Comment by barbarah** [comment]
Thank you for responding so quickly, I will downgrade for now.

**Comment by jetschni** [comment]
> Problem is fix by adding this to `/app/[locale]/layout.tsx`
> 
> ```
> export function generateStaticParams() {
>   return [{locale: 'en'}, {locale: 'de'}];
> }
> ```

How did you make this work with `next dev`?

Using the https://github.com/amannn/next-intl-example-next-13 as example. 

Updated next.js to the latest version (`13.1.6`) and everything works fine (next dev and next start).

If I add generateStaticParams() the following happens
```typescript
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "de" }];
}
```

**next dev**
`Page changed from static to dynamic at runtime /en, reason: headers`

**next start**
Everything works fine

**Comment by barbarah** [comment]
Sorry, this was incorrect of me. When I made that comment I was only testing production because there was the original problem. But with `next dev` and generateStaticParams() I got the same error you got.

I now use Next 13.1.6 and no generateStaticParams().

**Comment by jetschni** [comment]
Thank you! 

@amannn Any plans to support generateStaticParams() somehow? It would be nice if it would work in `next dev`

**Comment by amannn** [comment]
Currently `generateStaticParams` is not supported, please see the note in [the roadmap](https://next-intl-docs.vercel.app/docs/next-13/server-components#roadmap). You should be able to achieve the same performance characteristics with CDN caching though.

I'd still like to support SSG, but with the current feature set of Next.js I don't see a way how we could keep the ergonomics of `next-intl`. I hope that we can enable this though in the future!

**Comment by Jeroenrs** [comment]
@amannn This is an issue for us too. We use `generateStaticParams` to generate article pages for a blog – we cannot replace that, because we are loading an MDX file for every article from the file system (Node wouldn't know which files to include without it, so they are purged from the build). So SSG is not _just_ a performance upgrade for us – would love to see support for it soon :)

**Comment by amannn** [comment]
Hmm, I haven't tried that out yet! Note that [usage in Client Components fully supports SSG](https://next-intl-docs.vercel.app/docs/next-13/client-components), so maybe that's an option for you for these pages. I guess you could still make your MDX content server-only.
