### ISSUE TITLE
Default locale available via prefix

### ISSUE THREAD

**Issue by uvarov-frontend** [amannn/next-intl#202]
### Description

Hi! Cool plugin! 
There is a problem, I don't know if it should be, but the default locale is available through a prefix.
This is not good for SEO.

### Reproduction URL (CodeSandbox)

https://codesandbox.io/p/sandbox/next-intl-bug-template-forked-whh7qi

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Change address to `/en` manually
3. See error

### Expected behaviour

For example, if we set en as the default locale, then going to `example.com/en `should redirect to `example.com/` or give a 404 error.

**Comment by amannn** [comment]
Hey and thanks for the report!

It's not a bug but currently expected behavior. If you see a problem with this, can you share some resources that explain why this is a problem?

The background is that `next-intl` currently provides the same [i18n routing as Next.js provides for the `pages` directory](https://nextjs.org/docs/advanced-features/i18n-routing). By default, the middleware in the latest RSC beta returns [HTTP headers to indicate different languages](https://developers.google.com/search/docs/specialty/international/localized-versions#http).

**Comment by amannn** [comment]
I see your point. I have to say I haven't really researched this from an SEO perspective, so far `next-intl` simply follows the lead from Next.js. To make a call here I think it'd be important to do some research on official documentation from search engines.

**Comment by uvarov-frontend** [comment]
Understood, thanks for the reply.

**Comment by amannn** [comment]
This is fixed in `2.12.0-beta.3`!

**Comment by uvarov-frontend** [comment]
> This is fixed in `2.12.0-beta.3`!

Cool! Thank you for that!
