### ISSUE TITLE
Multiple namespaces from single useTranslations

### ISSUE THREAD

**Issue by darklight9811** [amannn/next-intl#217]
### Is your feature request related to a problem? Please describe.

To avoid creating tons of hooks to get multiple namespaces, allow merging namespaces in the useTranslations hook

### Describe the solution you'd like

``` typescript
// instead of this
const t1 = useTranslations("general")
const t2 = useTranslations("home")
const t3 = useTranslations("footer")

// this
const t = useTranslations("general", "home", "footer")
```

If there are conflicting keys, use the namespace import order to decide overriding order.

### Describe alternatives you've considered

Using multiple useTranslations can make the code really difficult since you need to keep track of multiple variables doing basically the same job. I see a lot of other tools allowing for something similar, so I think it would be cool if support for this was added. I can work on this to help the project.

**Comment by amannn** [comment]
This was already discussed before:
- https://github.com/amannn/next-intl/issues/41#issuecomment-875680830
- https://github.com/amannn/next-intl/issues/31

> Using multiple useTranslations can make the code really difficult

Yep, that's definitely not the way the library is intended to use—please see the section about [structuring messages](https://next-intl-docs.vercel.app/docs/usage/messages#structuring-messages).

It's fine though to pick another strategy if the recommended pattern doesn't suit your workflow.

In this case `next-intl` allows to load the messages from all namespaces at once:

```js
const t = useTranslations();

t('general.title')
```

> a lot of other tools allowing for something similar

Can you provide a link to them?

I might change my mind if there's enough demand for this feature, but since there's generally a different recommendation and already a workaround, this isn't a priority currently.

**Comment by benediktms** [comment]
I'd also like to chime in my support for multiple name spaces. Currently I work around this by simply using two seperate invocations of the translations hook, e.g.:
```tsx
const t = useTranslations("menubar");
const t_role = useTranslations("enums.role");
```

While this works and isn't really a problem (in some way it is nice to only get the correct autocomplete options), it would be nice to to be able to provide multiple name spaces at once.

**Comment by GhostvOne** [comment]
Looking for that too ... Sad there is no possibility to add multiple key at once

**Comment by heliocosta-dev** [comment]
This should be a MUST.
