### ISSUE TITLE
Docs next.js 13 - Usage in Client Components

### ISSUE THREAD

**Issue by ciruz** [amannn/next-intl#230]
### Description

First of all, next-intl works really well with next 13 and the app directory. Thank you for that.

I noticed something with the current docs:
https://next-intl-docs.vercel.app/docs/next-13/client-components#getting-started

You should import ``NextIntlClientProvider`` like so:

```javascript
import {NextIntlClientProvider} from 'next-intl/client';
```

But this gives a deprecation warning:

```javascript
/** @deprecated Should be imported from `next-intl`, not `next-intl/client`. */
export declare const NextIntlClientProvider: typeof NextIntlClientProvider_;
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

not-needed

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

no warnings if you follow the docs

**Comment by amannn** [comment]
> First of all, next-intl works really well with next 13 and the app directory. Thank you for that.

Great to hear, thank you! 🙌

> But this gives a deprecation warning:



Good point, I guess you're on the RSC beta then, right? The deprecation isn't in stable yet, so the docs are technically up-to-date currently. The deprecation is currently proposed in the beta version. However, I understand that this is a bit confusing currently because the beta docs also include a link to the Client Components page.

I've added a note on my todo list at https://github.com/amannn/next-intl/pull/149 to clean this up eventually when the RSC integration becomes stable. I'll close this issue for the time being, since this is noted.

Thanks again for the hint!
