### ISSUE TITLE
Error appeared after deploying to production

### ISSUE THREAD

**Issue by nixjs** [amannn/next-intl#246]
### Description

I am using turborepo and I have config but document and it worked when under local environment. But when going to production, it shows the following error:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/23132483/232178931-f711b457-f267-4ba6-8ea6-df02e2f20827.png">

After checking, I found it error in the code:
```typescript
export async function getServerSideProps({ locale }: GetServerSidePropsContext) {
    const messages = pick(await import(`../../messages/${locale || 'en'}.json`), Home.messages)
    console.log('message', locale, messages)
    return {
        props: {
            messages
        }
    }
}
```

If I remove the above snippet it works, but where do I get the message from?
Can you help me understand what's going on? Thanks

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

.

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

Can you help me understand what's going on? Thanks

**Comment by amannn** [comment]
Hello @nixjs, thank you for reporting your bug. As you probably read in the bug report form, the reproduction is mandatory. Unfortunately, I have to close issues without a reproduction as I can't diagnose what the issue is. Feel free to open a new bug report with a reproduction! Thank you for your understanding!
