### ISSUE TITLE
Documentation improvement (messages) | Next 13

### ISSUE THREAD

**Issue by sillasbernardo** [amannn/next-intl#312]
### Is your feature request related to a problem? Please describe.

I was replicating the steps in the "Server Components (beta)" section and I came across a detail problem that wasn't explicit in the documentation when passing translations as props from server components to client components.

Say I have a "en.json" file in message folder like this:

```json
{
   "navbar": {
     "home": "Home",
     "aboutus": "About us"
   }
}
```

The documentation shows I can access "navbar" property like below in server components:

```typescript
const t = useTranslations('navbar');

return <h1>{t('home')}</h1>
```

But let's say my "en.json" is as below:

```json
{
  "header": {
    "navbar": {
      "home": "Home",
      "aboutus": "About us"
    }
  }
}
```

If I pass the "navbar" property to a client component (navbar component) like below:

```typescript
  // Parent component (server)
  export default function ServerComponent(){
    const t = useTranslations("header");

    return (
      <ClientComponent translation={t("navbar")} />
    )
  }
```

Then translation will be a string "header.navbar", making it not possible to extract "home" property as ```translation("home")```, it means that this approach only works two levels deep in a json file. 

### Describe the solution you'd like

It would be much helpful if this was explicit in the documentation.

### Describe alternatives you've considered

I found the solution by checking the source code of the example from this [link](https://github.com/amannn/next-intl/tree/feat/next-13-rsc/examples/example-next-13) which's is accessing the second level as objects:

```typescript
description={t('navbar.home')}
```

**Comment by amannn** [comment]
Thanks for raising this discussion ticket.

This is not specific to Server Components, next-intl requires resolving the whole hierarchy with a call to `t`—otherwise you'll see an error. This is explained in [the structuring messages docs](https://next-intl-docs.vercel.app/docs/usage/messages#structuring-messages) at "How can I provide more structure for messages?".

I'm planning to restructure the docs to be App Router-first, hope this should clarify this in the future.
