### ISSUE TITLE
Alternative naming for server functions

### ISSUE THREAD

**Issue by milos-sikic-nimbus-tech** [amannn/next-intl#317]
### Is your feature request related to a problem? Please describe.

Not really a problem, more a concern about clarity.

### Describe the solution you'd like

Currently, the functions that are called within server components start with the `use` prefix. That's React's convention on how to name functions that are hooks.

Since you cannot run hooks in server components and it's unclear (afaik) whether that will ever be possible (or needed), I was wondering if it would make sense to rename the functions to something that couldn't lead developers to confuse them with hook calls (`getLocale`, `getTranslations`, for example)?

I'm very curious on your thought about this, and I apologize in advance if I'm missing something important here.

### Describe alternatives you've considered

Of course, we can use the library as-is, there is no problem with that, but since RSCs are such a new concept that introduce a completely new paradigm into React programming, I just thought that it might be good to consider these things.

**Comment by qnten** [comment]
Another problem when using this prefix is that eslint errors with `react-hooks/rules-of-hooks` when using the functions outside of components.

**Comment by amannn** [comment]
Thanks for raising this concern!

I did consider different APIs for usage in Server Components, but ultimately decided that a unified API is the way to go. The reason is that there can be components that can be used in either environment (no `'use client';` marker, no interactive APIs) and by using the same API we can make these components work in both environments.



> Another problem when using this prefix is that eslint errors with `react-hooks/rules-of-hooks` when using the functions outside of components.

They shouldn't be used there. As an escape hatch there are these APIs currently: https://next-intl-docs.vercel.app/docs/next-13/server-components#using-internationalization-outside-of-components. However, it's not yet clear if they'll make it into stable, so use them sparingly and only when you have no other choice.
