### ISSUE TITLE
Ability to remove path prefix from a specific locale other than the fallback language

### ISSUE THREAD

**Issue by wxh06** [amannn/next-intl#373]
### Is your feature request related to a problem? Please describe.

I would like to remove the prefix from path when the current language is `zh-CN`, while new visitors with unkown locales detected in `Accept-Language` can be redirected to fallback language `/en/` at the same time.

### Describe the solution you'd like

Change the `localePrefix` configuration from boolean to a string named `localeWithoutPrefix` that describes the locale without prefix in path.
Preserve `defaultLocale` as the meaning of "fallback language" or rename it to `fallbackLanguage` to avoid ambiguity.

### Describe alternatives you've considered

Add a new field `localeWithoutPrefix` to `RoutingBaseConfig` besides `defaultLocale` for backward compatibility.

**Comment by amannn** [comment]
Thanks for the report! This is quite a specific edge case, I think we won't add support for this for the time being.

You can however [compose the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares), detect non-`zh-CN` users there and redirect them as necessary instead of passing the request to the `next-intl` middleware.

Hope this helps!
