### ISSUE TITLE
Add TypeScript types to code in documentation

### ISSUE THREAD

**Issue by pschaub** [amannn/next-intl#389]
### Is your feature request related to a problem? Please describe.

While following the "Getting Started" guide for "Next.js 13: Internationalization (i18n) in Server Components", I noticed that my IDE complains about missing TypeScript types.

In particular, this part currently has no types in the documentation:
https://github.com/amannn/next-intl/blob/ff327ea485e3be4a5bf002a23a41292ec39dfd4d/docs/pages/docs/getting-started/app-router-server-components.mdx#L130

> TS7031: Binding element 'params' implicitly has an 'any' type.

### Describe the solution you'd like

Add TypeScript types to code in documentation

**Comment by amannn** [comment]
> TS7031: Binding element 'params' implicitly has an 'any' type.

It depends a bit on the settings you use for TypeScript, for some TypeScript setups this won't be an error. I agree though, that `noImplicitAny` is a good idea to use.

I just looked through all the docs and due to the way `next-intl` is designed, you never have to define any types for using the provided APIs (with the one exception being [`IntlMessages`](https://next-intl-docs.vercel.app/docs/typescript)). React Component APIs are in fact the only place where you have to type the props to pass strict type checking, but they aren't a concept that's introduced by `next-intl`.

The current stance is that the Next.js docs do a good job of educating about how to type props, so I think `next-intl` can take a shortcut here for brevity when explaining concepts.

I'm open to further feedback though in case more people run into this issue!
