### ISSUE TITLE
IntlError: FORMATTING_ERROR - 3.0.0-beta.8

### ISSUE THREAD

**Issue by mikekubn** [amannn/next-intl#397]
### Description

I updated next-intl to version "next-intl": "^3.0.0-beta.8", after updating we got following error:

```
IntlError: FORMATTING_ERROR: `createTranslator` only accepts functions for rich text formatting that receive and return strings.

E.g. t.rich('rich', {b: (chunks) => `<b>${chunks}</b>`})
    at base.rich (webpack-internal:///(sc_server)/./node_modules/use-intl/dist/src/core/createTranslatorImpl.js:37:27)
    at ExchangeRateChart (webpack-internal:///(sc_server)/./components/ExchangeRateChart/index.tsx:19:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'FORMATTING_ERROR',
  originalMessage: '`createTranslator` only accepts functions for rich text formatting that receive and return strings.\n' +
    '\n' +
    "E.g. t.rich('rich', {b: (chunks) => `<b>${chunks}</b>`})"
}
```

- I tried found why I got this error message, without result.
- I resolve my issue with downgraded to version `"next-intl": "3.0.0-beta.6"`.

Code snippet example:
```
// server component

const FooChart = async ({
  className,
  locale,
}: FooChart Props): Promise<React.ReactElement> => {
  const t = await getTranslator(locale);
  const translatedBottomText = t.rich("bottomText", {
    phone: (chunks) =>
      (
        <a className="hover:underline" href={`tel:${chunks}`}>
          {chunks}
        </a>
      ) as unknown as string,
    olbLink: (chunks) =>
      (
        <a
          className="hover:underline"
          href="https://www.test.eu"
          target="_blank"
        >
          {chunks}
        </a>
      ) as unknown as string,
  });
```

```
// Rich text from locize

  "bottomText": "The values shown are indicative. In order to obtain a current and individual course offer, please contact us at: <phone>+48 22 208 00 99</phone>. You can check the current odds at any time on <olbLink>OLB Link</olbLink>.",
```

Anybody have same issue? 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

mentioned above

### Reproduction description

1. update next-intl to last beta version `"next-intl": "^3.0.0-beta.8"`
2. use `npm run dev`
3. you should see error mentioned above

### Expected behaviour

The version `3.0.0-beta.8` should work same as version `3.0.0-beta.6` without error for rich text.

**Comment by ReesMorris** [comment]
Same issue here.

We had:
```
"read_more": "Read more <hidden>about {title}</hidden>"

{t.rich('read_more', {
  title,
  hidden: val => (<span className={sharedStyles.hideAccessibly}>{val}</span>) as any
})}
```

Based on the suggested change, this would become:

```
{t.rich('read_more', {
  title,
  hidden: val => `<span>${val}</span>`
})}
```

but this doesn't seem to parse the HTML, instead rendering:

`Read more <span>about Custom title</span>`

 (I also have no idea if we'd still be able to add classes this way?)

**Comment by amannn** [comment]
Thanks for the question! This is in fact intentional.

`getTranslator` is really [intended to be used in Metadata & Route Handlers](https://next-intl-docs.vercel.app/docs/environments/metadata-route-handlers). In  React Server components (as well as Client Components), you should [make use of `useTranslations`](https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#applocalepagetsx).

```tsx
// Before
async function Component() {
  const t = await getTranslator(locale, 'Component');
  // ...
}

// After
function Component() {
  const t = useTranslations('Component');
  // ...
}
```

Previously to 3.0.0-beta.8, `getTranslator` could return a `ReactNode` for rich text formatting. This was a subtle bug I overlooked in the initial implementation, since `ReactNode` can't be consumed in any meaningful way in Metadata & Route Handlers (however you might want to return plain HTML from an API endpoint for example). I've aligned this behavior in https://github.com/amannn/next-intl/pull/395.

In case you were using `getTranslator` as a workaround for static rendering, please refer to check [the up-to-date information on currently available workarounds](https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#static-rendering).

Sorry for the churn, I hope you can find a reasonable solution for your use case!

**Comment by amannn** [comment]
Yep, you'd have to split it in two:

```tsx
export const Footer = async (props: FooterProps) => {
  const { locale } = props;
  const footer = await getFooter(locale); // fetches data from a CMS
  return <FooterContent footer={props.footer} />;
}

const FooterContent = (props: FooterContentProps) => {
  const { footer } = props;
  const t = useTranslations('footer');

  return (
    <footer>
      {t.rich('published_by', {
        link: text => <Link href={footer.publisher}>{text}</Link>
      })}
    </footer>
  );
}
```

See also: https://github.com/amannn/next-intl/discussions/276#discussioncomment-6382900

**Comment by amannn** [comment]
Great to hear that it works for you!

Also thank you so much for the sponsorship, this is incredibly kind of you and encouraging! ❤️❤️❤️

**Comment by mikekubn** [comment]
@amannn Thank you for your fast answer. Probably I should use combination of client provider `NextIntlClientProvider` and `Server Components`, if I understand correctly.

**Comment by mikekubn** [comment]
Thank you guys! ❤️ 👍
