### ISSUE TITLE
usePathname is null

### ISSUE THREAD

**Issue by max-frai** [amannn/next-intl#424]
### Description

Hello, I have client component which implements language switch logic. To make it, I should have Link component with currect page src + locale attribute.

So to get current path I use:

```
import { usePathname } from "next-intl/client"
console.log(`Pathname from next intl: ${pathname}`);
```

And it's always returned as **null**. That's way component is rendered SSR, but no current path available. If I use original usePathname from nextjs, it returns correct full path.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

-

### Reproduction description

```
"use client"

const FRONT_LANGUAGES = ["en", "de"];

import { useSearchParams } from "next/navigation"
import { Link } from "next-intl"

import { usePathname } from "next-intl/client"

// This works okay, no null
// import {usePathname } from 'next/navigation';

import React, {  useMemo } from "react"

export const LangSwitcher = ({locale}) => {
    const pathname = usePathname()
    const searchParams = useSearchParams()

    // null
    console.log(`Pathname from next intl: ${pathname}`);

    const url = searchParams?.toString()?.length
        ? `${pathname}?${searchParams}`
        : pathname

    const langButtons = useMemo(
        () =>
            FRONT_LANGUAGES?.map((language) => (
                <Link href={url || ""} locale={language}>{language}</Link>
            )),
        [url],
    )

    return <div>{langButtons}</div>
}

```

### Expected behaviour

usePathname from next-intl should return current path, returns null.

**Comment by amannn** [comment]
Thank you for the report. Unfortunately the reproduction is missing, I'm sure you've read in the issue template that it's required. I can unfortunately not look into your issue if that's the case. Please add a reproduction if you think this is a bug, otherwise I'll have the close the issue—I hope you understand.

Here's an example that uses `usePathname` and works well: https://codesandbox.io/p/sandbox/github/amannn/next-intl/tree/main/examples/example-next-13?file=%2Fsrc%2Fcomponents%2FNavigationLink.tsx%3A13%2C1-14%2C1
