### ISSUE TITLE
Custom cookie name for locale

### ISSUE THREAD

**Issue by NickNaso** [amannn/next-intl#486]
### Is your feature request related to a problem? Please describe.

Hi everybody and thanks for this wonderful work. I'm using `next-intl v3.0.0-beta.14` all works fine for my use case, but it would good to have the possibilities to set the `COOKIE_LOCALE_NAME`  (today it's fixed and its value is `NEXT_LOCALE`). 
The problem is that my Next.js application should works together with other web application that use another cookie name to handle the language.

### Describe the solution you'd like

I think that a possible solution could be to allow to pass a new parameter to es. `localeCookie` to `createMiddleware` function like reported below:

```js
import createMiddleware from 'next-intl/middleware';

export default createMiddleware({
  // A list of all locales that are supported
  locales: [''en', 'it'],

  // If this locale is matched, pathnames work without a prefix (e.g. `/about`)
  defaultLocale: 'en',

  localeCookie: 'MY-CUSTOM-LOCALE-COOKIE'
});

export const config = {
  // Skip all paths that should not be internationalized. This example skips the
  // folders "api", "_next" and all files with an extension (e.g. favicon.ico)
  matcher: ['/((?!api|_next|.*\\..*).*)'],
};

```

### Describe alternatives you've considered

I think that the alternative should be to update the values of the cookie in the middleware and about that  is there any suggusted workaround to synchronize the value of `NEXT_LOCALE` cookie with another one?

**Comment by amannn** [comment]
This question came up before here: https://github.com/amannn/next-intl/pull/166

We probably won't add this in the near future since I currently have a particular use case in mind for https://github.com/amannn/next-intl/pull/149 where it might be necessary to know the name of the cookie on the client side. If the name is configurable at the middleware level, we wouldn't be able to know its name directly on the client side, except if we add another layer on top, e.g. a cookie that the middleware adds to responses, which contains the name of the cookie.

If there's more demand for this in the future I might consider it though.

For the time being, to solve your use case, you can [compose the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) and configure `NEXT_LOCALE` as a cookie on the request object, before the `next-intl` middleware receives the request. Potentially you can also read `NEXT_LOCALE` from the response object and optionally sync it back to your other cookie.

Hope this helps!

**Comment by NickNaso** [comment]
Thank you your suggestion helped me.❤️

**Comment by nkabour** [comment]
Would this help in configuring NEXT_LOCALE to be secure cookie? is it possible to enable secure cookies in the future?

**Comment by 413n** [comment]
Just wanted to add my 2 cents. In my use case I wanted to modify the cookie of NEXT_LOCALE to be available cross subdomain so I had to rewrite the cookie after createMiddleware to change the domain option. It would be good to consider also the CookieOptions if this feature will be developed.

**Comment by 1mehdifaraji** [comment]
@413n Hey, any updates on the subdomain ? Can you share some code about this ?

**Comment by 413n** [comment]
Hey @1mehdifaraji , I've migrated off Next.js some time ago, but from the history I have found this.

```typescript
// i18n.ts
import createMiddleware from "next-intl/middleware";
import { defaultLocale, locales } from "./config";

export const localeMiddleware = createMiddleware({
  locales,
  // If this locale is matched, pathnames work without a prefix (e.g. `/about`)
  defaultLocale,
  localePrefix: "as-needed",
});

// src/middleware.ts
export const middleware = (request: NextRequest) => {
  const response = localeMiddleware(request);

  const NEXT_LOCALE = response.cookies.get("NEXT_LOCALE")?.value;

  if (NEXT_LOCALE) {
    // Override NEXT_LOCALE to add cross-subdomain readability
    response.cookies.set("NEXT_LOCALE", NEXT_LOCALE, {
      httpOnly: true,
      sameSite: "lax",
      path: "/",
      domain: `.${request.nextUrl.hostname}`,
      maxAge: 60 * 60 * 24 * 365, // 1 year
    });
  }

  return response;
};
```

**Comment by amannn** [comment]
The cookie can be customized in newer versions of `next-intl`: [`localeCookie`](https://next-intl.dev/docs/routing/configuration#locale-cookie)
