### ISSUE TITLE
Documentation for using next-intl with SSR instead of static generation

### ISSUE THREAD

**Issue by dustinsgoodman** [amannn/next-intl#50]
**Is your feature request related to a problem? Please describe.**
I need to internationalize my site that has both static content that can be translated and server generated content to display on that page. Hence, I need to use both `getStaticsProps` and `getServerSideProps`. However, Next.js does not allow me to use both functions so either I have to opt into no translations or opt into no dynamic content on load. I can't afford to lose either feature so I need a path that I can use `next-intl` in both ways.

**Describe the solution you'd like**
If there's a way to load translations at the app level instead of statically per page, I'd take that solution. Using `getStaticProps` isn't going to continue to work for my use case.

**Describe alternatives you've considered**
I can't find it anymore but someone at one point suggested doing something in `_document` or `_app` where you preload. I'd be okay with this solution but I can't find a way to do it again.

**Additional context**
I am trying to get Vercel to make both prop rendering methods available https://github.com/vercel/next.js/discussions/11424

**Comment by amannn** [comment]
Hey @dustinsgoodman,

sure, I think you have these options:
1. Return your messages from `getServerSideProps` of a page and pass them to the provider in `App`.
2. You can use `App.getInitialProps` to load common messages across all pages and pass them to the provider. I [used to do that in the example in this repo](https://github.com/amannn/next-intl/blob/97804dca72dc393ee202b50988dbb0f903a48d2d/packages/example/src/pages/_app.tsx), but switched to `getStaticProps` since it's the way Next.js recommends.
3. A mixture of the two.

Does that help?

**Comment by amannn** [comment]
@dustinsgoodman Were you able to get this working in your app?

**Comment by dustinsgoodman** [comment]
Discovered today that your option 1 works better than I expected. Seems like Next handles those server side props on page nav if you use next/link which is really nice and meets our needs. Thanks for your feedback. 😄

**Comment by amannn** [comment]
Ok, that's great to hear! 🙂

Can this issue be closed then or is there something to improve about the documentation from your perspective?

**Comment by dustinsgoodman** [comment]
I need to think on the docs issue. I feel like there could have been something so we didn't chase our tails for a bit, but I'm not entirely sure if it's your library's responsibility to clarify that. I'll close and reopen a new issue if I think of something helpful. 😉
