### ISSUE TITLE
Faulty regular expression in middleware causes valid URLs to not work

### ISSUE THREAD

**Issue by skonky** [amannn/next-intl#504]
### Description

The default regular expression that is used by the matcher is faulty. After a solid 3 hours of debugging I finally found the culprit and it was this library.

Strange nobody has encountered this before but I suggest changing the regexp you provide in the docs.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-yv52yj?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Flayout.tsx%3A5%2C30

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on the broken link in the "nav menu"
3. Voila it's broken now :)

### Expected behaviour

URLs that end with a period should work as they're valid URLS and need no encoding. If you want to see if the end of the pathname is a file (i.e. favicon.ico) do not use a wildcard match after the period. (.*)

**Comment by amannn** [comment]
Thank you so much for sharing your finding! May I ask which regex you ended up with?

It doesn't seem so trivial to me. In your example the middleware doesn't match the URL because it has two dots, e.g. `/something/Mars%20B.` would work as far as I can tell. The `.V.` part is incorrectly matched as a file extension. 

I started work on a PR here: https://github.com/amannn/next-intl/pull/505

In case you have some input, that would be great!

**Comment by skonky** [comment]
I haven't found out a proper regexp but the one provided in the docs will always fail if you have a period anywhere in the URL you can validate that in the codesandbox

https://yv52yj-3000.csb.app/something/Mars%20BV.   [FAIL]
https://yv52yj-3000.csb.app/something/Mars%20B.V.  [FAIL]
https://yv52yj-3000.csb.app/something/Mars%20B.V   [FAIL]
https://yv52yj-3000.csb.app/something/Mars%20BV    [PASS]
