### ISSUE TITLE
Error When Updating next-intl to 3.0.0-rc.4:  'unstable_setRequestLocale' Requires Static Rendering but 'cookies' Are Necessary for Auth

### ISSUE THREAD

**Issue by abiddraws** [amannn/next-intl#559]
### Description

**Description:**
When attempting to update the 'next-intl' package to version 3.0.0-rc.4, it insists on using static rendering through the 'unstable_setRequestLocale' API. However, my application relies on the use of cookies for authentication, and this requirement for static rendering is causing build-time errors.

Error Message: 
```
Dynamic server usage: Page couldn't be rendered statically because it used `cookies`
```

If I run without ```unstable_setRequestLocale``` , I am getting the below error
```
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering
```

**Additional Information:**
- My application requires the use of cookies for authentication, which is non-negotiable.
- I am using the following code to configure 'supabase' with 'cookies':

```
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
const supabase = createServerComponentClient({ cookies });
```

Possible Solutions:
I am looking for guidance on how to resolve this issue. Is there a workaround that would allow me to continue using cookies for authentication while still utilizing 'next-intl' version 3.0.0-rc.4 and its 'unstable_setRequestLocale' feature for static rendering?

Your assistance and insights would be greatly appreciated. Thank you!

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-hk8yrr?file=%2Fpackage.json%3A5%2C15

### Reproduction description

1. Update the 'next-intl' package to version 3.0.0-rc.4.
2. Configure 'unstable_setRequestLocale' to use static rendering.
3. Attempt to build the application.
```
const locales = ["en", "ar"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}):{
  unstable_setRequestLocale(params.locale);
// remaining code
}
```

### Expected behaviour

The application should build successfully, even if cookies are being used for authentication.

**Actual Behavior:**
The build process fails with the error message: "Page couldn't be rendered statically because it used 'cookies'."

**Comment by amannn** [comment]
I currently see this error message when running your sandbox:

<img width="567" alt="Screenshot 2023-10-12 at 09 34 30" src="https://github.com/amannn/next-intl/assets/4038316/d7fdc907-4154-401a-9d66-4023dd07d185">

But yes, if you use cookies in your app code, you can't use static rendering. Therefore the fix is to remove `generateStaticParams` & `unstable_setRequestLocale` and your app should work.

Does that help?

**Comment by abiddraws** [comment]
If I remove the `generateStaticParams  `& `unstable_setRequestLocale`  I get this error while building app 
```
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering,
```

**Comment by amannn** [comment]
Not sure if I'm missing something, but when I open your reproduction I see this error:

<img width="588" alt="Screenshot 2023-10-12 at 10 47 14" src="https://github.com/amannn/next-intl/assets/4038316/212e9ced-f4fe-4aa2-9e7f-6b247614b453">

There seems to be the wrong version of `next-intl` in the CodeSandbox.

After re-installing the RC, I get this error:

<img width="590" alt="Screenshot 2023-10-12 at 10 47 53" src="https://github.com/amannn/next-intl/assets/4038316/afaf5f8c-9498-4a97-aec4-0ed66f52e4ac">

That's correct, since there's no `i18n.ts` file that's required for Server Components usage.

**Comment by abiddraws** [comment]
@amannn Please check from https://github.com/abiddraws/MyNextJs . If you try to build `npm run build` the app you will get the error 
```Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering```

**Comment by amannn** [comment]
The issue is this line here: https://github.com/abiddraws/MyNextJs/blob/1b4bb4cd148107c6a8d636c953f63e642d975b1f/app/page.tsx#L1

The navigation APIs from `next-intl` can only be used within the `[locale]` segment. You should import from `next/navigation` in `app/page.tsx`.

I made a note in https://github.com/amannn/next-intl/pull/149 to improve the error message here. Thanks for the report!

**Comment by abiddraws** [comment]
🌟 Thanks a million! Your help made my day! 🙌
