### ISSUE TITLE
middleware size extremely large on build

### ISSUE THREAD

**Issue by t2pellet** [amannn/next-intl#599]
### Description

Hi, I was trying to deploy my Next.js site on Vercel, and its failing due to the middleware.ts file being too big:
```
Error: The Edge Function "src/middleware" size is 2.47 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size
```

![image](https://github.com/amannn/next-intl/assets/4323034/1046cee5-800b-4880-b444-66029b6692c4)

I tried looking around a bit and couldn't seem to grasp why the middleware would need to be that large.

My middleware is purely just the `next-intl` middleware, nothing else:
```
import createMiddleware from 'next-intl/middleware';
import { languages } from '@/types';

export default createMiddleware({
  locales: languages,
  defaultLocale: 'en',
});

export const config = {
  matcher: ['/((?!api|_next|_vercel|.*\\..*).*)'],
};
```

I'm using:
```
    "next": "13.5.4",
    "next-intl": "^3.0.0-rc.7",
    "react": "^18.2.0",
    "react-dom": "^18",
```    

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/t2pellet/tenzin.live

### Reproduction description

Steps to reproduce:
1. Use `next-intl` middleware in `middleware.ts`
2. Try to deploy to Vercel

### Expected behaviour

The middleware.ts file should be a smaller/more reasonable size

**Comment by t2pellet** [comment]
I've dug around a bit more and it appears to be a Nextjs issue after all -- its bundling things it shouldn't be with the middleware for some reason.

Closing!

**Comment by amannn** [comment]
Thanks for investigating! Can you link to the issue on the Next.js side?

**Comment by apavlinovic** [comment]
@amannn @t2pellet I think this needs to be reopened. It is not nextjs, it is the fact that we are including messages on every request in the i18n configuration of Next Intl. 

Basically, when you write

export default getRequestConfig(async ({ locale }) => {
    return {}
}

Where you import JSON files, those JSON files are bundled by webpack, since you explicitly ask us to import them. This is causing the bloat in middleware size – this is not a NextJS problem, it's a next-intl problem!

**Comment by amannn** [comment]
Let's continue the discussion in #814
