### ISSUE TITLE
Improved compatibility with Next js fetch caching

### ISSUE THREAD

**Issue by alexalligator** [amannn/next-intl#612]
### Is your feature request related to a problem? Please describe.

Firstly, massive thanks for your work with next-intl. 👍 

We use nextjs with a headless CMS so we send lots of fetch requests to our backend rest API.

Next caches fetches by default (which we want) but if one of certain conditions arises then it stops caching (for all requests).

One of these conditions is using cookies and headers because nextjs (very reasonably) assumes that there must be some per-user logic involved which means using cached data would be a bad idea. 

So using cookies or headers essentially turns of fetch caching.

This is only my understanding of how nextjs works and I maybe wrong but here is a link to the relevant docs: [Nextjs docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-fetch)

### Describe the solution you'd like

I understand that next-intl uses cookies and headers to detect and set the current locale. I understand that using headers and cookies it what most people want and that fetch caching being disabled is correct behaviour.

However, I have set `localeDetection: false` in my middleware which should mean "Only consider url path when determining locale, never the Accept-Language header or cookies." 

Is there a way to completely avoid next-intl code interacting with headers and cookies when localeDetection is false? So that nextjs no longer treats the route as user specific and will therefore happily cache fetches?

### Describe alternatives you've considered

I have been systematically cutting out next-intl from my components and routes to see when fetch caching starts again and it definitely seems like next-intl, in its current form, is preventing nextjs from caching fetches.

**Comment by amannn** [comment]
Thank you so much for the kind words, glad to hear that `next-intl` works well for you! 🙌 

That's an interesting question. I just ran a small experiment and observed that the order when a header gets read matters:

**Scenario 1**

```tsx
import {headers} from 'next/headers';

type Data = {
  id: string;
  joke: string;
  status: number;
};

export default async function FetchPage() {
  // ✅ Cache hit
  const data1: Data = await fetch('https://icanhazdadjoke.com/', {
    headers: {
      Accept: 'application/json'
    }
  }).then((response) => response.json());

  // ❌ Cache miss (due to usage of headers)
  const data2: Data = await fetch('https://icanhazdadjoke.com/?test', {
    headers: {
      Accept: 'application/json',
      'Accept-Language': headers().get('Accept-Language') as string
    }
  }).then((response) => response.json());

  return (
    <>
      <p>{data1.joke}</p>
      <p>{data2.joke}</p>
    </>
  );
}
```

```
 GET /fetch 200 in 170ms
 │ GET https://icanhazdadjoke.com/ 200 in 0ms (cache: HIT)
 │  │ GET https://icanhazdadjoke.com/?test 200 in 140ms (cache: SKIP)
 │  │  │  Cache missed reason: (auto cache)
```

**Scenario 2**

Now, if you swap the requests around:

```tsx
import {headers} from 'next/headers';

type Data = {
  id: string;
  joke: string;
  status: number;
};

export default async function FetchPage() {
  // ❌ Cache miss (due to usage of headers)
  const data2: Data = await fetch('https://icanhazdadjoke.com/?test', {
    headers: {
      Accept: 'application/json',
      'Accept-Language': headers().get('Accept-Language') as string
    }
  }).then((response) => response.json());

  // ❌ Cache miss too, although the fetch request doesn't depend on headers
  const data1: Data = await fetch('https://icanhazdadjoke.com/', {
    headers: {
      Accept: 'application/json'
    }
  }).then((response) => response.json());

  return (
    <>
      <p>{data1.joke}</p>
      <p>{data2.joke}</p>
    </>
  );
}
```

```
 GET /fetch 200 in 354ms
 │ GET https://icanhazdadjoke.com/?test 200 in 195ms (cache: SKIP)
 │  │  Cache missed reason: (auto cache)
 │  │ GET https://icanhazdadjoke.com/ 200 in 123ms (cache: SKIP)
 │  │  │  Cache missed reason: (auto cache)
```

---

To be honest, I don't know if this is expected behavior from Next.js, or if this is a bug. At least based on this example, I don't see a reason why the second request can't be cached in the second scenario.

This is a reduced example of the situation you seem to be encountering. This might require some research on the Next.js issue tracker to see if this is expected behavior or not, and possibly adding a bug report.

In case you're interested to look further into this, I'd be curious if you can find something! Fetch logging can be turned on [in `next.config.js`](https://nextjs.org/docs/app/api-reference/next-config-js/logging).

---

That being said, for your practical situation you might want to use the [static rendering integration of `next-intl`](https://next-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app/docs/getting-started/app-router#static-rendering), this avoids reading headers altogether for all call sites that follow the invocation of `unstable_setRequestLocale `.


Hope this helps!

**Comment by alexalligator** [comment]
Thanks for such a detailed and quick reply!

I've also noticed what you're seeing; that as soon as something touches headers it "poisons" all future requests on the route... from that point on nothing gets cached.

Can I use the static rendering integration you mention without actually statically rendering the whole site?

**Comment by amannn** [comment]
> Can I use the static rendering integration you mention without actually statically rendering the whole site?

Absolutely, yes!

I've added a note to https://github.com/amannn/next-intl/pull/149 to make the docs about this clearer, thanks for the feedback!

**Comment by alexalligator** [comment]
Seems to work perfectly for my needs, thank you for your help.

**Comment by amannn** [comment]
Great to hear! I'll close this issue for the time being then.

I'd be curious if there's room for improvement on the Next.js side (see https://github.com/amannn/next-intl/issues/612#issuecomment-1803750649), but that requires a bit more research and possibly a bug report on their side.

**Comment by amannn** [comment]
(forgot to close)
