### ISSUE TITLE
Support arrays of namespaces

### ISSUE THREAD

**Issue by Goldziher** [amannn/next-intl#646]
### Is your feature request related to a problem? Please describe.

The issue is how to reuse translations efficiently. Currently only a single namespace can be used by `useTranslations`, which means we cannot have shared namespaces.

### Describe the solution you'd like

```typescript
const t = useTranslations("namespace1", "namespace2", "namespace3")
```

### Describe alternatives you've considered

All alternative libraries support this. The issue they have is bad integration with next. But this feature is really really important.

**Comment by amannn** [comment]
Thank you for the report, I definitely understand your request!

This has been discussed a few times before, the latest being https://github.com/amannn/next-intl/issues/217.

There are currently no plans to support this because:
1. It would make the TypeScript integration significantly more difficult (if possible at all)
2. It increases the API surface for something that can already be achieved today (`useTranslations()`—i.e. no namespace), possibly getting in the way of a potential feature in the future
3. It introduces ambiguity which message to resolve to when there's overlap (e.g. `ns1.title` and `ns2.title`)

The [structuring messages](https://next-intl-docs.vercel.app/docs/usage/messages#structuring-messages) section in the docs has more information on this topic.

As mentioned, I understand the request, but I think this API is for the time being not a good direction for `next-intl`, especially since there are escape hatches.

Hope this helps!
