### ISSUE TITLE
When `trailingSlash: true`, `createLocalizedNavigation` doesn't work properly

### ISSUE THREAD

**Issue by Micu22** [amannn/next-intl#668]
### Description

The language switcher doesn't work on homepage when trailingSlash is set to true in next.config.js

Also, the pathnames param sent to the createLocalizedPathnamesNavigation() function, has to have no-trailing slash, to work regardless of the trailingSlash setting in next.config.js. This is just ok, just annoying, maybe it can be fixed alongside the homepage problem.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/amannn/next-intl/tree/main/examples/example-app-router

### Reproduction description

Steps to reproduce:
1.  Install the example-app-router
2.  set trailingSlash to true in next.config.js
3.  open homepage and switch the language

### Expected behaviour

Setting trailingSlash to true, should keep all translation mechanisms intact.

**Comment by amannn** [comment]
> The language switcher doesn't work on homepage when trailingSlash is set to true in next.config.js

For me this works without an issue. Can you submit a reproduction that shows the error?

**Comment by amannn** [comment]
I can access the CSB, yes!

I can see these errors:
- The German link renders as http://localhost:3000/de/pathnames/ (should be `/de/pfadnamen`, seems to be a problem in the `Link` component)
- http://localhost:3000/de/pfadnamen/ is a 404 (seems to be a problem in the middleware)

Are these the ones which you are seeing too?

Generally, maybe we could adapt the internal handling to work both with trailing slashes and without.

If you're interested in working on a fix, here's the relevant code:
- [Tests for `createLocalizedPathnamesNavigation`](https://github.com/amannn/next-intl/blob/main/packages/next-intl/test/navigation/react-client/createLocalizedPathnamesNavigation.test.tsx)
- [Implementation for `createLocalizedPathnamesNavigation`](https://github.com/amannn/next-intl/blob/main/packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.tsx)
- [Relevant handling in the middleware](https://github.com/amannn/next-intl/blob/97324c5179201c40ba5e23a17ba444a5cba705e0/packages/next-intl/src/middleware/middleware.tsx#L121-L162)
- [Tests for the middleware](https://github.com/amannn/next-intl/blob/97324c5179201c40ba5e23a17ba444a5cba705e0/packages/next-intl/test/middleware/middleware.test.tsx#L296)

**Comment by vordgi** [comment]
@amannn Hello!

I noticed a problem for navigation with this: the localized path is taken from the object by the key (_current pathname_). The current pathname is a pathname without a slash at the end (`/pathnames`). In the object, the keys can indicate with a slash at the end (`/pathnames/`).

There are several ways to solve this:

Check if trailing slash is included and if yes - make pathname with a slash at the end, if not - without. The downside here is that the user is limited by this and needs to know this detail.

Ignore this issue and write in the doc that all keys must be without a slash at the end (_except for the root page_)

Bring the object of localized pathnames and current pathname to one form - f.e. without a slash at the end (current pathname `/pathname`, and process pathnames: `{'/pathnames/': '/something/'}` -> `{'/pathnames': '/something/'}`). The problem here is that after processing, you still need to control the trailing slash and configure it in the final path. Otherwise, unnecessary redirects may appear.
