### ISSUE TITLE
Allow for a defaultLocale override

### ISSUE THREAD

**Issue by cipriancaba** [amannn/next-intl#753]
### Is your feature request related to a problem? Please describe.

Currently, there is no way to override the defaultLocale, it will always be set based on the `accept-language` header. The following config does nothing for me, it's always the browser header that decides

```
const handleI18nRouting = createIntlMiddleware({
    locales: ["en", "de"],
    defaultLocale: "de",
    localePrefix: 'never',
    localeDetection: true,
  })
```

### Describe the solution you'd like

I want to be able to override the defaultLocale by giving more priority to the `defaultLocale` config option

I think the order of resolving the locale should be default locale `prio 3` and accept language should be `prio 4`
https://github.com/amannn/next-intl/blob/f8cdcf263825e53935cccd4de56868007ff14993/packages/next-intl/src/middleware/resolveLocale.tsx#L57

### Describe alternatives you've considered

Can't seem to find a workaround, maybe I can try initially setting NEXT_LOCALE to `de` in the middleware

**Comment by amannn** [comment]
> I think the order of resolving the locale should be default locale `prio 3` and accept language should be `prio 4`

If that would be the case, the accept-language header would never be used (since a `defaultLocale` is mandatory).

Can you share more details on your use case?

By [composing the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares), you should have plenty of freedom. E.g. to force a particular locale for a given request, you can set the `defaultLocale` dynamically, limit the available `locales`, turn off `localeDetection` etc.

If you have a very special use case where the `next-intl` middleware doesn't help much, you can also [implement your own](https://github.com/amannn/next-intl/issues/653).

**Comment by kneza23** [comment]
So how we can override the the locale for users for the first time. Since defaultLocale is not a priority, what can we do so that for example default language for all users be German but later if they want to switch to English, they can do that and it would be remembered for all other visits to the application?

**Comment by amannn** [comment]
You can add a redirect if a user requests the app and no `NEXT_LOCALE` cookie is available from a previous visit. I'll close this issue now since it seems to be a usage question.
