### ISSUE TITLE
[Docs]: Add more information about RootLayout

### ISSUE THREAD

**Issue by Tockra** [amannn/next-intl#862]
### Link to page

https://next-intl-docs.vercel.app/docs/getting-started/app-router#layout

### Describe the problem

HI,

I'm a little bit confused about the given information regarding the changes in the layout.tsx .
NextJS docuementation says "The root layout is defined at the top level of the app directory and applies to all routes. This layout is required and must contain html and body tags, allowing you to modify the initial HTML returned from the server." https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required .

After adding the next-intl stuff you can not fullfill this requirement anymore because you have already the html tag in the nested LocaleLayout. 
Further I'm not sure if you can build a senseful RootLayout then anymore and if you still need it. Most stuff you which to add to your root layout should be nested in the html tag. So your "real" RootLayout is now in [locale]/layout.tsx .
I think the documentation should address this differences between the original next js documentation and the usage of next-intl.

What do you think?
T

**Comment by amannn** [comment]
Good question! There's unfortunately a bit of a conflict in the Next.js docs in regard to the root layout. The docs mention that it's required to have a layout with basic HTML right within the `app` folder, however the official example from Vercel [uses a nested root layout for i18n](https://github.com/vercel/next.js/blob/canary/examples/app-dir-i18n-routing/app/%5Blang%5D/layout.tsx). In order to set a `lang` attribute on `html` it's required to use a nested root layout.

There was a discussion about this on the Next.js issue tracker, but I can't find it anymore. This is a similar one though: https://github.com/vercel/next.js/issues/52722. In the other issue this conflict was pointed out but there was no official resolution 🤷‍♂️.

From what I can tell, using a nested layout seems to work fine, but these gotchas apply:
1. When adding [a root `not-found` page](https://next-intl-docs.vercel.app/docs/environments/error-files#catching-non-localized-requests), you need to create a pass-though root layout
2. Users have occasionally reported issues with parallel and intercepted routes (see #255) but AFAIK these were somewhat unstable for a longer time anyway—I'm unsure if the issues were related to the moved root layout

Hope this helps!
