### ISSUE TITLE
Intercepting + Dynamic Routes, Jumping the page causes a forced refresh

### ISSUE THREAD

**Issue by zhengzhu-1m** [amannn/next-intl#873]
### Description
- https://github.com/vercel/next.js/issues/62207
When accessing dynamic interception routes, the page will be forced to refresh.
 
Note:   
1. The bug will only be triggered in the vercel deployment environment 
2. The local development environment works normally
3. If you don't use the `next-intl` library, it works fine

### Mandatory reproduction URL

https://github.com/bosinc/next-bug

### Reproduction description

Steps to reproduce:
1. https://next-bug-vert.vercel.app
2. click `Page any` button

### Expected behaviour

 Retain the multi-language mode, intercept routes will work normally, and will not force a refresh of the page

**Comment by amannn** [comment]
Possibly another instance of https://github.com/amannn/next-intl/issues/255, it's unclear to me if there's anything `next-intl` can do here. This might be something that needs to be addressed upstream.

**Comment by huyitan** [comment]
I have same issues on the production build. 
Development work fine.

**Comment by tquann286** [comment]
Same, interception routes work fine in development mode, but it causes hard navigation on production

**Comment by huyitan** [comment]
i think this bug is caused by nextJS config build. It's rewrite route " /:locale/signal/:id" to "/__NEXT_EMPTY_PARAM__/(.)signal/:id", missing "locale" param. Then we use 

unstable_setRequestLocale, which throws an error when nextjs prefetch Intercepting routes.

`
Rewrites

┌ source: /:locale/signal/:id
└ destination: /__NEXT_EMPTY_PARAM__/(.)signal/:id
`

Workaround for me: remove unstable_setRequestLocale (pages will currently opt into [dynamic rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering))

**Comment by sayandedotcom** [comment]
any update??
