### ISSUE TITLE
Type safe message access

### ISSUE THREAD

**Issue by dnbkr** [amannn/next-intl#90]
**Describe the solution you'd like**
I would find it very helpful if message access was type safe, for example:

given messages like this:

```json
# messages/en.json

{
  "Components": {
    "Greeting": {
      "body": "hello, world!"
    }
  }
}
```

it would be good to have typescript fail on these two examples:

```ts
const t = useTranslations("Components.Foo")
```

```ts
const t = useTranslations("Components.Greeting")
t("bar")
```

**Additional context**
I appreciate this could be hard for splitting message sets across different pages (as you may not know which message set is available at any given time) so having all return types be possibly undefined could be a compromise. The aim of the feature is not so much to guarantee access safety but to facilitate auto completion of keys to avoid typos etc.

**Comment by amannn** [comment]
Thank you for opening this issue, I'd be interested in this too as it will enhance the DX quite a bit!

I'm not sure yet what's the best way to tackle this. I can think of the following approaches:
1. Providing a generic parameter to every call site. This is implementation-wise probably the easiest, but the ergonomics are not really good.
```tsx
useTranslations<Messages>(…)
```
2. Providing a factory function to provide the generic parameter. This would allow to provide the parameter only once, but it changes the way you import every module – so also not ideal IMO.
```tsx
const {useTranslations, …} = createTypedIntlModules<Messages>(…);
```
3. Use the ability from TypeScript to override an interface (e.g. [like Emotion does it](https://emotion.sh/docs/typescript#define-a-theme)).

Not sure if there are other options, but from these I'd largely prefer the third one.

The other aspect is how to create the type. I'd guess there are some utilities from TypeScript to generate this, I'd image something like `typeof` to work here. This would have to be done in user land since we don't make assumptions about how or where the messages are stored. So this would largely be a documentation topic.

If you have other ideas or are interested in helping out to implement this please let me know!

**Comment by amannn** [comment]
Hey @coffeedoughnuts,

I found some time to look into this topic and I think I've found a solution that works!

Would you like to try out a prerelease version of this feature in your app? I'd be really happy about some feedback if you have the time.

Here's how to upgrade:
```sh
npm uninstall next-intl
npm install next-intl@2.4.1-alpha.4
```

… and here are the docs for the new feature: https://next-intl-git-feat-90-type-safe-messages-amann.vercel.app/docs/usage/typescript.

/cc @ishigami since you accidentally found an earlier prerelease of this feature in https://github.com/amannn/next-intl/issues/94 😁.

Also /cc @andrevenancio since you already provided helpful feedback in the past! Maybe you're curious 🙂

**Comment by coffeedoughnuts** [comment]
Hey - I'm so sorry, I had some time off from work and completely forgot to reply to you after I returned!

I shall try your solution later today and report back; thank you for looking into it!
