### ISSUE TITLE
`notFound()` behaviour

### ISSUE THREAD

**Issue by kevinmitch14** [amannn/next-intl#938]
### Description

- When I navigate to a page that does not exist, the regular 404 page is shown.
- When I manually invoke `notFound()`, I get the error message `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
- I've read through the repo's issues and docs and see that it's recommended to add custom `not-found.tsx` inside `[locale]`.

For reference my setup looks like this:
```
app
├── [locale]
│   └── [tenant]
│       └── layout.tsx (<html lang={params.locale}>)
```

When I put `not-found.tsx` inside `[locale]`, along with a `layout.tsx`, nothing happens.

I actually need to place the `not-found.tsx` inside `[tenant]` in order for it to trigger correctly. Is this the expected behavior? It would be great to understand what exactly is going on here!
```
app
├── [locale]
│   └── [tenant]
│       └── layout.tsx
│       └── not-found.tsx
```

It feels a bit unnatural, I just want to use Next.js default behaviour, i18n is not a product requirement for 404 pages.

---

To give a little more context which is also in the repo. We are using rewrites to handle a multi tenant application, each tenant lives on a subdomain. So we are doing something like below.

```jsx
request.nextUrl.pathname = `/${subdomain}${path}`;
return NextResponse.rewrite(request.nextUrl);
```

When hooking this up with `createIntlMiddleware()`, it seems to also cause some issues. Logging the path from the incoming middleware request looks like this, it just keeps growing in an infinite loop of sorts. When I use `localePrefix: "never"`, I don't get this issue however.
```bash
{ subdomain: 'dev', path: '/' }
{ subdomain: 'dev', path: '/en/dev' }
{ subdomain: 'dev', path: '/en/dev/en/dev' }
{ subdomain: 'dev', path: '/en/dev/en/dev/en/dev' }
{ subdomain: 'dev', path: '/en/dev/en/dev/en/dev/en/dev' }
```

### Mandatory reproduction URL

https://github.com/kevinmitch14/next-intl-bug-repro-app-router.git

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Navigate to dev.locahost:3000 to view "home" page
3. Navigate to dev.localhost:3000/random to trigger a `notFound()` 
4. See blank screen

---

1. In `createIntlMiddleware()`, remove `localePrefix: "never"` and observe behaviour. 

### Expected behaviour

No need for a custom not-found.tsx.

**Comment by kevinmitch14** [comment]
In the [Middelware - Additonal Rewrites](https://next-intl-docs.vercel.app/docs/routing/middleware#example-additional-rewrites) docs, it uses  the following snippet.
```tsx
const [, locale, ...segments] = request.nextUrl.pathname.split('/');
```

However, the locale is not available on initial visit for example when visiting - http://dev.localhost:3000. The result is:
```tsx
{ locale: '', segments: [] }
```

**Comment by kevinmitch14** [comment]
Hey @amannn, any ideas on this?

**Comment by amannn** [comment]
Hey @kevinmitch14,

as far as I can tell, there are primarily two issues in your example app:

1. The `body` tag is missing
2. The locale prefix was inconsistently handled

I've fixed your example here: https://github.com/amannn/kevinmitch14-next-intl-bug-repro-app-router. Please see the most recent commits for reference. I initially got the example working with `localePrefix: 'always'` and then refactored to `localePrefix: 'never'`.

Note that if you add additional rewrites on top of the middleware to remove the tenant, the navigation APIs will break too—so you'll have to implement those yourself. However, you can still use all hooks like `useTranslations` in components, the situation is rather that `next-intl` can't assist you much with routing concerns. Generally, this is closely related: https://github.com/amannn/next-intl/issues/653

I'll close this issue as the fixed example seems to work as expected and because this is rather a usage question.

Hope this helps!

**Comment by kevinmitch14** [comment]
Hey @amannn thanks for your response, greatly appreciated. I will look into this today and report any findings!

**Comment by HazimAlper** [comment]
Hi @amannn, I reviewed the codes you sent. I think I'm in a similar situation. I'm trying to make a not-found file under the app folder. What I want is to show a 404 in the user's language.

Currently, I have created 2 not found files in the project. One is under /app/[locale] and the other is directly in /app.

A url like "/wrong" triggers the not found under /app/[locale] and I can show the user a 404 page containing locale information. 
However, when I type "/wrong/also", not found in /app works and there is no locale information there. 

In both cases, I want not found under /app/[locale] to work so that I always have the locale information. Can you help me? Where am I doing wrong or thinking wrong?
